name: R-CMD-check.yaml

permissions:
  id-token: write
  contents: write
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  workflow_call:

jobs:
  R-CMD-check:
    runs-on: ubuntu-24.04
    env:
      RENV_CONFIG_REPOS_OVERRIDE: "https://p3m.dev/cran/__linux__/noble/latest"
    steps:
      - uses: actions/checkout@v4
      # - name: Install system dependencies
      #   run: sudo apt-get install -y cmake libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libnode-dev libx11-dev pandoc
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check
      # - uses: r-lib/actions/check-r-package@v2